Все слышали про известное приложение для знакомств - Tinder. Приложение предоставляет простой интерфейс для выбора понравившегося человека. Сейчас в Google Play более 100 миллионов установок.

Используя данные из VK, нужно сделать сервис намного лучше, чем Tinder, а именно: чат-бота “VKinder”. Бот должен искать людей, подходящих под условия, на основании информации о пользователе из VK:

Возраст,
пол,
город,
семейное положение.
У тех людей, которые подошли по требованиям пользователю, получать топ-3 популярных фотографии профиля и отправлять их пользователю в чат вместе со ссылкой на найденного человека.
Популярность определяется по количеству лайков и комментариев.

За основу можно взять код из файла basic_code.py.
Как настроить группу и получить токен можно найти в инструкции.

Входные данные

Имя пользователя или его id в ВК, для которого мы ищем пару.
если информации недостаточно нужно дополнительно спросить её у пользователя.

Требования к сервису:

Код программы удовлетворяет PEP8.
Получать токен от пользователя с нужными правами.
Программа декомпозирована на функции/классы/модули/пакеты.
Результат программы записывать в БД.
Люди не должны повторяться при повторном поиске.
Не запрещается использовать внешние библиотеки для vk.






В работе есть несколько проблем. Которые, в частности, не позволили запустить ваш проект.

В некоторых местах неверно расставлены исключения, например:

try:
id_couple = f'https://vk.com/id{utilizer_vk.test_photos(owner_id=str(couple[0]))[1]}'
all_photos = utilizer_vk.test_photos(owner_id=str(couple[0]))[0]
except vk_api.exceptions.ApiError:
write_msg(event.user_id, f'Ошибка api Вконтакте')
Вы ждёте здесь ошибку апи, но могут возникать ошибки TypeError, IndexError в строке:

id_couple = f'https://vk.com/id{utilizer_vk.test_photos(owner_id=str(couple[0]))[1]}'

И это гораздо более вероятное событие. Здесь нужно либо менять логику работы, либо ставить исключения на эти ошибки.
Так же


try:
response = requests.get(f"{self.base_url}/method/users.search",
params={**self.general_params(), **params}).json()["response"]["items"]
except vk_api.exceptions.ApiError:
pass
except KeyError:
pass
except:
print("Error")
Когда вы делаете так


except KeyError:
pass
Вы говорите, если возникла ошибка ключа, то это штатная ситуация - ничего страшного.

Но это означает что ваш response будет неопределённым, а вы будете обращаться к нему. И это уже не выглядит т как штатная ситуация.
В таких случая нужно обязательно предпринимать какие-то действия, например возвращать None и обрабатывать этот случай при вызове функции.

И ещё:


try:
shown_people = utilizer_vk.test_people(age - 1, age + 1, sex, user_city, relation, removal)
except vk_api.exceptions.ApiError:

Отлавливание ошибки vkapi.exceptions.ApiError в этом месте избыточно при учёте что она у вас уже ловится внутри testpeople()

Наведите пожалуйста порядок с исключениями, уберите лишние поставьте недостающие.
Главное правило - исключения должны быть расставлены максимально 'адресно', где ждёте ошибку там и ставите. (обязательно исправить)

Везде делаете проверку if <что-то> is not None: это эквивалентно проверке if <что-то>: (желательно исправить)

Используете глобальные переменные, это плохой стиль. (желательно исправить)

Декомпозиция кода. В вашем коде интерфейс бота переплетен с внутренними функциями и взаимодействию с БД. Это очень плохой стиль, нужно декомпозировать этот код и вынести всё что касается интерфейса в отдельные функции, всё что касается взаимодействия с апи в отдельные, внутреннюю логику в отдельные. (обязательно исправить)
